### ISSUE TITLE
Incorrect implementation of Android isTouchIdEnabled function

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-biometry#15]
Android implementation of function `isTouchIdEnabled` works incorrect - e.g. it will return `true` if the device has a biometric sensor, but no fingerprints have been added yet. I think that this is not the behavior of the function that a developer expects. 
https://github.com/icerockdev/moko-biometry/blob/ed6f6137e950dcf458895bc6bffc9f047068cb5d/biometry/src/androidMain/kotlin/dev/icerock/moko/biometry/BiometryAuthenticator.kt#L87
At the moment, the correct way is to use androidx library: https://developer.android.com/reference/androidx/biometric/BiometricManager#canAuthenticate(int)
Something like this

```kotlin
return BiometricManager.from(context).run {
    canAuthenticate(BiometricManager.Authenticators.BIOMETRIC_WEAK) == BiometricManager.BIOMETRIC_SUCCESS
}
```

**Comment by Alex009** [comment]
will be released in 0.3.0
