### ISSUE TITLE
When should be used setPackageManager?

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-biometry#7]
https://github.com/icerockdev/moko-biometry/blob/master/biometry/src/androidMain/kotlin/dev/icerock/moko/biometry/BiometryAuthenticator.kt#L42

**Comment by ZiXOps** [comment]
when you need to check is TouchId enabled on android via isTouchIdEnabled(): Boolean
it's need to be set in activity or fragments onCreate

**Comment by Alex009** [comment]
@ZiXOps why this not implemented inside `bind` method? 

https://github.com/icerockdev/moko-biometry/blob/master/biometry/src/androidMain/kotlin/dev/icerock/moko/biometry/BiometryAuthenticator.kt#L28
